CREATE TABLE `inventory_summary` (
  `summary_id` int(15) unsigned NOT NULL AUTO_INCREMENT,
  `company_id` int(11) unsigned NOT NULL,
  `code_type` varchar(4) NOT NULL COMMENT 'buy / sell / empty = both',
  `vendor_id` int(11) NOT NULL COMMENT 'verdor_id',
  `product_id` varchar(100) NOT NULL,
  `product_name` text NOT NULL,
  `product_buy` text NOT NULL COMMENT 'ชื่อตอนซื้อ',
  `balance` double NOT NULL,
  `sell_price` double unsigned NOT NULL,
  `buy_price` double unsigned NOT NULL,
  `vat` varchar(4) NOT NULL,
  `discount` float unsigned NOT NULL,
  `update_dt` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `status` varchar(10) NOT NULL DEFAULT 'show' COMMENT 'show/hide/obsolete',
  `bom_status` varchar(10) NOT NULL,
  `acc_sell` varchar(15) NOT NULL,
  `acc_buy` varchar(15) NOT NULL,
  `category` varchar(100) NOT NULL,
  `category_buy` varchar(100) NOT NULL,
  `unit` varchar(100) NOT NULL,
  `tag` varchar(100) NOT NULL,
  `thumbnail` tinytext NOT NULL,
  `std_cost` double unsigned NOT NULL,
  `acc_cost` varchar(15) NOT NULL,
  `po_rule` varchar(10) NOT NULL,
  `sell_barcode` varchar(50) NOT NULL,
  `buy_barcode` varchar(50) NOT NULL,
  `acc_whgr` varchar(15) NOT NULL COMMENT 'a/c code เมื่อรับสินค้า',
  `acc_whmr` varchar(15) NOT NULL COMMENT 'a/c code เมื่อเบิกสินค้า',
  `last_cal` datetime NOT NULL COMMENT 'ครั้งสุดท้ายที่คำนวนต้นทุน',
  `last_cal_cost` double unsigned NOT NULL COMMENT 'ราคำคำนวนล่าสุด',
  `type` varchar(7) NOT NULL COMMENT '"" = normal, serial, lot',
  `obsolete` varchar(3) NOT NULL,
  `brand` varchar(100) NOT NULL,
  `pvat` varchar(4) NOT NULL,
  `other_unit` text NOT NULL,
  `acc_begin` varchar(50) NOT NULL COMMENT 'a/c code สินค้าต้นงวด',
  `acc_end` varchar(50) NOT NULL COMMENT 'a/c code สินค้าปลายงวด',
  `acc_inventory` varchar(50) NOT NULL COMMENT 'a/c code สินค้าคงเหลือ',
  `activate_maxstock` int(1) unsigned NOT NULL DEFAULT 0 COMMENT '1 = ใช้ maxstock / 0 = ไม่ใช้ maxstock',
  `activate_reorder` int(1) unsigned NOT NULL DEFAULT 0 COMMENT '1 = ใช้ reorder / 0 = ไม่ใช้ reorder',
  `buy_detail` text NOT NULL COMMENT 'เงื่อนไขการซื้อ',
  `commission1` double unsigned NOT NULL,
  `commission2` double unsigned NOT NULL,
  `floor_price` decimal(16,6) unsigned NOT NULL COMMENT 'ราคาต่ำสุดที่ขายได้',
  `import_id` int(10) unsigned NOT NULL,
  `ma` double(20,6) unsigned NOT NULL COMMENT 'moving average cost / unit',
  `maximum_stock` double NOT NULL,
  `originate` varchar(100) NOT NULL,
  `other` text NOT NULL,
  `reorder_point` double NOT NULL,
  `restrict` int(1) unsigned NOT NULL DEFAULT 0 COMMENT '0 = ติดลบไม่ได้ | 1 = ติดลบได้',
  `sell_detail` text NOT NULL COMMENT 'เงื่อนไขการขาย',
  `so` double NOT NULL,
  `tr_rule` varchar(10) NOT NULL,
  `url` text NOT NULL,
  `department` varchar(255) NOT NULL,
  PRIMARY KEY (`summary_id`),
  UNIQUE KEY `product_id_company_id` (`product_id`,`company_id`),
  KEY `company_id` (`company_id`),
  KEY `product_id` (`product_id`),
  KEY `sell_barcode` (`sell_barcode`),
  KEY `buy_barcode` (`buy_barcode`),
  KEY `company_id_reorder_point` (`company_id`,`reorder_point`),
  KEY `import_id` (`import_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;